import numpy as np
mylist=[1,2,3,4,5]
length=len(mylist)
a=10
#list转为矩阵
mymatrix=np.mat(mylist)
#list乘10是重复十次
print(a*mylist)
#矩阵乘法
print(a*mymatrix)
print(type(mylist),type(mymatrix))
#0矩阵
myZero=np.zeros([3,5])
print(myZero)
#1矩阵
myOne=np.ones([5,3])
print(myOne)
#随机矩阵
myRandom=np.random.rand(3,4)
print(myRandom)
#单位矩阵
myEye=np.eye(3)
print(myEye)
#自己写矩阵
mylist2=np.mat([[1,2,3],[4,5,6],[7,8,9]])
print(mylist2)
#矩阵乘法
print(pow(mylist2,2))
#转制
print(mylist2.T)
#求矩阵行列
[m,n]=np.shape(mylist2)
print(m,n)
#复制
print(mylist2.copy())
#linalg里面有各种矩阵求解的操作：求值、A*、A-、求zhi等
print(np.linalg.det(mylist2))